# Generated by Django 5.0.1 on 2024-09-07 06:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("freehtml", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="comphtml",
            old_name="crerated_at",
            new_name="created_at",
        ),
    ]
