# Generated by Django 5.0.1 on 2024-09-07 10:14

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("freehtml", "0002_rename_crerated_at_comphtml_created_at"),
    ]

    operations = [
        migrations.AddField(
            model_name="comphtml",
            name="extrascript",
            field=models.TextField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
