# Generated by Django 5.0.1 on 2024-09-08 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("freehtml", "0003_comphtml_extrascript"),
    ]

    operations = [
        migrations.AlterField(
            model_name="comphtml",
            name="extrascript",
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name="comphtml",
            name="extrastyle",
            field=models.TextField(null=True),
        ),
    ]
