# Generated by Django 5.0.1 on 2024-09-08 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("freehtml", "0004_alter_comphtml_extrascript_alter_comphtml_extrastyle"),
    ]

    operations = [
        migrations.AlterField(
            model_name="comphtml",
            name="extrascript",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="comphtml",
            name="extrastyle",
            field=models.TextField(blank=True, null=True),
        ),
    ]
