# Generated by Django 5.1.1 on 2024-09-20 02:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("freehtml", "0005_alter_comphtml_extrascript_alter_comphtml_extrastyle"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="comphtml",
            options={"verbose_name": "compHtml", "verbose_name_plural": "compHtmls"},
        ),
    ]
