# Generated by Django 5.0.1 on 2024-09-03 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("flashcard", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="flashcardset",
            name="is_public",
            field=models.BooleanField(default=False),
        ),
    ]
