# Generated by Django 5.1.1 on 2024-09-20 02:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("flashcard", "0002_flashcardset_is_public"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="flashcard",
            options={
                "ordering": ["cardset", "knowledge_level"],
                "verbose_name": "Flashcard",
                "verbose_name_plural": "Flashcards",
            },
        ),
        migrations.AlterModelOptions(
            name="flashcardset",
            options={
                "ordering": ["title"],
                "verbose_name": "Flashcard Set",
                "verbose_name_plural": "Flashcard Sets",
            },
        ),
        migrations.AlterModelOptions(
            name="progress",
            options={
                "ordering": ["-last_reviewed"],
                "verbose_name": "Progress",
                "verbose_name_plural": "Progresses",
            },
        ),
    ]
