# Generated by Django 5.1.1 on 2024-09-17 02:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("appObjectStorage", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="storedfile",
            name="is_deleted",
            field=models.BooleanField(default=False),
        ),
    ]
