# Generated by Django 5.0.1 on 2024-06-17 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myblog', '0002_category_tag_rename_sno_blog_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='featuredblog',
            name='type',
            field=models.CharField(choices=[('carousel', '轮播展示'), ('all-top', '全站首位展示'), ('all-normal', '全站普通展示'), ('category-top', '分类首位展示'), ('category-normal', '分类普通展示')], default='all', max_length=20),
        ),
    ]
