# Generated by Django 5.0.1 on 2024-09-03 16:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("myblog", "0003_alter_featuredblog_type"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="contact",
            options={
                "ordering": ["-time"],
                "verbose_name": "留言",
                "verbose_name_plural": "留言",
            },
        ),
    ]
