# Generated by Django 5.1.1 on 2024-09-20 02:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("myblog", "0004_alter_contact_options"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="blog",
            options={"verbose_name": "blog", "verbose_name_plural": "blogs"},
        ),
        migrations.AlterModelOptions(
            name="category",
            options={"verbose_name": "category", "verbose_name_plural": "categories"},
        ),
        migrations.AlterModelOptions(
            name="contact",
            options={
                "ordering": ["-time"],
                "verbose_name": "contact",
                "verbose_name_plural": "contacts",
            },
        ),
        migrations.AlterModelOptions(
            name="featuredblog",
            options={
                "verbose_name": "featured blog",
                "verbose_name_plural": "featured blogs",
            },
        ),
        migrations.AlterModelOptions(
            name="tag",
            options={"verbose_name": "tag", "verbose_name_plural": "tags"},
        ),
    ]
