# Generated by Django 5.1.1 on 2024-09-05 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("appUser", "0002_alter_profile_options_alter_profile_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="image",
            field=models.ImageField(
                default="appUser/default.jpg", upload_to="appUser/profile_pics"
            ),
        ),
    ]
