# Generated by Django 5.1.1 on 2024-09-05 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("appUser", "0003_alter_profile_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="image",
            field=models.ImageField(
                default="default.jpg", upload_to="appUser/profile_pics"
            ),
        ),
    ]
